version: "3.4"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  
  query-node:
    image: query-node:latest
    restart: unless-stopped
    build: 
      dockerfile: docker/Dockerfile.query-node
      context: ./
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8080:${GRAPHQL_SERVER_PORT}"
    depends_on: 
      - db
    

  processor:
    image: hydra-processor:latest
    restart: unless-stopped
    build: 
      dockerfile: docker/Dockerfile.processor
      context: ./
    env_file:
      - .env
    environment:
      - INDEXER_ENDPOINT_URL=https://sumer-indexer.joystream.app/graphql
      - DB_HOST=db
      - POLL_INTERVAL_MS=300
      - TYPEORM_HOST=db
      - DEBUG=hydra-processor:*
    command: ["yarn", "processor:start"]
  
  
