name: publish
on:
  # When Release Pull Request is merged
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - hydra_v1
    types: [closed]

env:
  CI: true
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      ## Check if the PR was labeled with 'release:hydra-cli'
      - name: Get hydra-cli release label 
        uses: Dreamcodeio/pr-has-label-action@master
        id: checkLabel
        with:
          label: release:hydra-cli
      - name: Checking release:hydra-cli PR label
        run: echo "${{ steps.checkLabel.outputs.hasLabel }}" 
      - name: Checkout
        if: steps.checkLabel.outputs.hasLabel == 'true'
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        if: steps.checkLabel.outputs.hasLabel == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Git Identity
        if: steps.checkLabel.outputs.hasLabel == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install and bump minor version
        if: steps.checkLabel.outputs.hasLabel == 'true' && github.event.pull_request.merged == true
        run: |
          yarn 
          yarn workspace @dzlzv/hydra-cli build 
          yarn workspace @dzlzv/hydra-cli version --patch
          git push 
      # Define ${RELEASE_VERSION}
      - name: Set Release Version
        if: steps.checkLabel.outputs.hasLabel == 'true'
        shell: bash -ex {0}
        run: |
          RELEASE_VERSION=$(node -p 'require("./packages/hydra-cli/package.json").version')
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Create Git Tag
        if: steps.checkLabel.outputs.hasLabel == 'true' && github.event.pull_request.merged == true
        uses: azu/action-package-version-to-git-tag@v1
        with:
          version: ${{ env.RELEASE_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "hydra-cli-v"
      - name: Create Release
        id: create_release
        if: steps.checkLabel.outputs.hasLabel == 'true' && github.event.pull_request.merged == true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: hydra-cli:v${{ env.RELEASE_VERSION }}
          # Copy Pull Request's tile and body to Release Note
          release_name: "Hydra-cli ${{ github.event.pull_request.title }}"
          body: |
            ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
      - name: Publish
        if: steps.checkLabel.outputs.hasLabel == 'true' && github.event.pull_request.merged == true
        run: |
          yarn workspace @dzlzv/hydra-cli publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}